const studentsActionType ={
    FETCH_ALL_STUDENTS: 'FETCH_ALL_STUDENTS',
    FETCH_SINGLE_STUDENT: 'FETCH_SINGLE_STUDENT',
    ADD_NEW_STUDENT: 'ADD_NEW_STUDENT',
    DELETE_STUDENT: 'DELETE_STUDENT',
    UPDATE_STUDENT: 'UPDATE_STUDENT'
}

export default studentsActionType;