const campusesActionType ={
    FETCH_ALL_CAMPUSES: 'FETCH_ALL_CAMPUSES',
    FETCH_SINGLE_CAMPUS: 'FETCH_SINGLE_CAMPUS',
    ADD_NEW_CAMPUS: 'ADD_NEW_CAMPUS',
    DELETE_CAMPUS: 'DELETE_CAMPUS',
    UPDATE_CAMPUS: 'UPDATE_CAMPUS'
}

export default campusesActionType;